apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: go-receiver-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-receiver-role
subjects:
- kind: ServiceAccount
  name: go-receiver-sa
  namespace: monitoring