apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-receiver
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-receiver
  template:
    metadata:
      labels:
        name: go-receiver
    spec:
      serviceAccountName: go-receiver-sa
      containers:
      - name: go-receiver
        image: dimitarnzhv/go-receiver:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: receiver-secrets
              key: AUTH_TOKEN
        - name: REDSHIFT_HOST
          valueFrom:
            secretKeyRef:
              name: receiver-secrets
              key: REDSHIFT_HOST
        - name: REDSHIFT_PORT
          valueFrom:
            secretKeyRef:
              name: receiver-secrets
              key: REDSHIFT_PORT
        - name: REDSHIFT_USER
          valueFrom:
            secretKeyRef:
              name: receiver-secrets
              key: REDSHIFT_USER
        - name: REDSHIFT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: receiver-secrets
              key: REDSHIFT_PASSWORD
        - name: REDSHIFT_DATABASE
          valueFrom:
            secretKeyRef:
              name: receiver-secrets
              key: REDSHIFT_DATABASE
        - name: REDSHIFT_SSLMODE
          value: "disable"
        resources:
          requests:
            cpu: "1000m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"