apiVersion: v1
kind: Service
metadata:
  name: go-receiver-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    name: go-receiver
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    name: go-receiver
