apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-labeler
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: node-labeler-sa 
          containers:
          - name: label-nodes
            image: bitnami/kubectl:latest
            command: ["/bin/bash", "/scripts/label-nodes.sh"]
            volumeMounts:
            - name: script
              mountPath: /scripts/label-nodes.sh
              subPath: label-nodes.sh
          restartPolicy: OnFailure
          volumes:
          - name: script
            configMap:
              name: node-labeler-script