apiVersion: v1
kind: Secret
metadata:
  name: nextjs-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.secrets.app.nextauthSecret | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.app.googleClientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.app.googleClientSecret | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.app.githubClientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.app.githubClientSecret | b64enc | quote }}
  DB_HOST: {{ .Values.secrets.db.host | b64enc | quote }}
  DB_PORT: {{ .Values.secrets.db.port | b64enc | quote }}
  DB_USER: {{ .Values.secrets.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.db.password | b64enc | quote }}
  DB_NAME: {{ .Values.secrets.db.name  }}
