apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        jsonData:
          httpMethod: POST
      - name: Doris
        type: mysql
        access: proxy
        url: doriscluster-fe-service.monitoring.svc.cluster.local:9030
        database: dzhelev_db
        user: dzhelev
        secureJsonData:
          password: dzhelev@123
        jsonData:
          sslmode: disable
