apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-manager-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: event-manager-app
  template:
    metadata:
      labels:
        name: event-manager-app
    spec:
      containers:
      - name: event-manager-app
        image: dimitarnzhv/event-manager-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: BACKEND_URL
          value: "http://go-receiver-service:5000"
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: receiver-secrets
              key: AUTH_TOKEN
        - name: DASHBOARD_URL
          value: "https://grafana.dzhelev.itgix.eu/public-dashboards/8044a7280939410990f76c63ecbdfb14"