apiVersion: v1
kind: Service
metadata:
  name: event-manager-app-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    name: event-manager-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: event-manager-app
