apiVersion: v1
kind: PersistentVolume
metadata:
  name: doris-meta-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/doris-meta

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: doris-logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/doris-logs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: doris-be-logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/doris-be-logs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: doris-be-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/doris-be-storage