apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: postgres
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s