apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  namespace: url-shortener-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: shortlink.dzhelev.itgix.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service 
            port:
              number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-manager-app-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: dashboard.dzhelev.itgix.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: event-manager-app-service 
            port:
              number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kps-grafana-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.dzhelev.itgix.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kps-grafana 
            port:
              number: 80