apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  namespace: url-shortener-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: a5247991bb0a34f4a91991d982f7d391-d890f48954b06f60.elb.eu-central-1.amazonaws.com # The URL of the LoadBalancer
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service 
            port:
              number: 3000