apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  namespace: url-shortener-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: a45b4fca34e46495194948a8fc8b8588-a3e545aa2af00bc3.elb.eu-central-1.amazonaws.com # The URL of the LoadBalancer
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-service 
            port:
              number: 3000