apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    name: nextjs-url-shortener
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: nextjs-url-shortener
